### ISSUE TITLE
Have tab numbers match Cmd+N shortcut

### ISSUE THREAD

**Issue by huyz** [kg8m/chrome-show-tab-numbers#1]
I usually have tab groups and I collapse them. Chrome's Cmd+N shortcuts do the smart thing: they ignore the collapsed tabs when counting.
Could this extension do the same so that hitting Cmd+N opens the corresponding tab?

**Comment by kg8m** [comment]
@huyz 
Thanks for the request. I didn't care for collapsed tab groups because I don't use the feature. I will consider supporting this feature soon.

**Comment by kg8m** [comment]
Collapsed tab groups have been supported by #2. I'll release a new version later. Thanks!

**Comment by huyz** [comment]
Thanks @kg8m !
