### ISSUE TITLE
For the Relative case, signed numbers "+/-" as a helpful option ? 

### ISSUE THREAD

**Issue by YxT3** [kg8m/chrome-show-tab-numbers#100]
Most probably this must have been considered long time before, but still, 
for additional clarity with Relative numbering, and to better distinguish this mode from Absolute numbering, *Signed* tab numbers might be desirable, like "-1, -2" etc. upward ( if not even "-1-, -2-" etc.) and "+1, +2" downward.

**Comment by kg8m** [comment]
@YxT3 
Hi, thank you for the opinion.

I have released [v1.5.0](https://github.com/kg8m/chrome-show-tab-numbers/releases/tag/v1.5.0) and added an option to toggle the display of the
“+” and “-” signs next to the relative numbers. The new version will be published after the review.
