### ISSUE TITLE
PDF missing tab number fix

### ISSUE THREAD

**Issue by Lewis-Bright** [kg8m/chrome-show-tab-numbers#106]
I have a local branch with a fix for the pdf tabs not showing numbers. It uses `chrome.tabs` to query the tab name, which returns a value even if `document.title` is blank for a pdf reader tab.

I don't have permissions to make a branch on this project so I can't raise a PR. Let me know what you'd like me to do, if you want to incorporate the fix

**Comment by kg8m** [comment]
@Lewis-Bright 
Thank you for the information, and I apologize for the delayed response.

You’re absolutely right. As you mentioned, it’s not possible to create a branch directly in this repository. Could you please fork this repository (, create a branch in your fork for the development), and then submit a pull request from your fork to this repository?
