### ISSUE TITLE
[FR] keyboard shortcut for temporarily removing tab number

### ISSUE THREAD

**Issue by huyz** [kg8m/chrome-show-tab-numbers#16]
When I bookmark or clip the current web page to, say, Evernote, I don't the tab number in the title.
Could you add keyboard shortcut that will remove the tab number from the current tab? And hitting it again could then bring it back.

Optionally there could also be another keyboard shortcut to disable/reenable the extension so that all the tab numbers disappear/reappear.

**Comment by kg8m** [comment]
Thanks for the feature request. I'll give it a try soon.

**Comment by kg8m** [comment]
@huyz 
Hi. I have released [v1.2.0](https://github.com/kg8m/chrome-show-tab-numbers/releases/tag/v1.2.0), that supports keyboard shortcuts to toggle tab numberting of tabs. Please wait for its publication on Chrome Web Store.

**Comment by kg8m** [comment]
For your information, extension context menu to toggle tab numberting has been also supported in v1.2.0.

**Comment by huyz** [comment]
Woo-hoo! thanks
